### PR TITLE
RFC: Add NoSemicolonAfterShortEchoTagFixer

### PR DESCRIPTION
**Pull request by bytehead**
I've noticed this (html5 template) code style all over the templates in the `contao/*` ecosystem but there is no fixer for this kind of code style.

As I want to use this code style at our daily work, I've come up with a fixer for that.

WDYT? Would this also be useful for Contao or should I just make my own ECS package for that?

### CODE REVIEW

**Comment by leofeyer** [comment]
I think it would be useful for Contao, too. However, we have only applied this logic to `T_OPEN_TAG` and not `T_OPEN_TAG_WITH_ECHO` so far.

```php
<?= $this->foo ?>
<?php echo $this->foo; ?>
``` 

Would it be ok to limit the fixer to `<?=` or does it no longer make sense to you then?

**Comment by bytehead** [comment]
Sure thing, see 21dfe23.

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @bytehead.

**Comment by bytehead** [comment]
🎉

**Pull request merged**
